### ISSUE TITLE
Problem with printing images from lximage-qt

### ISSUE THREAD

**Issue by travis-82** [lxqt/lximage-qt#263] opened 2019-08-14 10:33 UTC
Sorry devs, It might seems ridiculous, but have you ever tried to print images from lximage-qt?

On Manjaro (kernel 4.19 lts, Lxqt 0.14.1) I can not print images correctly using my hp 4300 printer. Image printed as a quarter of full size per sheet. No matter what option I choose, it needs 4 sheet to print the image. I set Hp Device Manager option for image printing to  "Fit to page", but lximage keep to print image quarterly. This problem doesn't happen with other image viewers like GIMP and Nomacs. I didn't check this problem on other distros as Manjro is the only distro which I use.

Sorry for my english

**Comment by tsujan** [comment] 2019-08-14 14:31
lximage-qt doesn't print anything; CUPS does (Hello, Apple!). All options are in Qt print dialog.

**Comment by gerhardbeck** [comment] 2019-11-25 21:24
Hi,
I wanted to join @travis-82 
I tried to print a picture on a 10x15 picture paper. I configured all right in the QT print dialog, but in LXimage is one important dialog missing: "resize to paper size".
You find it e.g. in qpdfview
Can it be that there are different ways in different programs which settings are shown in the print dialogue?

**Comment by tsujan** [comment] 2019-11-26 04:13
My bad; I shouldn't close this.

Reopened to be investigated. Printing to PDF isn't good and now I think the problem is in our code.

**Comment by tsujan** [comment] 2019-11-26 04:26
OK, a glance at the code shows that the current behavior is intentional: the image is divided to "columns" when it can't be put into a single page.

However, IMO, that isn't practical. Instead, it's better to resize the image when it's too big. Other image viewers/editors I tested did it that way. We might want to add an option for it later but, for now, resizing seems better.

**Comment by tsujan** [comment] 2019-11-26 06:29
If you want to test it, the fix is here: https://github.com/lxqt/lximage-qt/pull/291

**Comment by gerhardbeck** [comment] 2019-11-26 09:14
Thanks @tsujan for having a second look at it!

**Comment by tsujan** [comment] 2019-11-26 09:23
You're welcome. It was a valid bug report; I should have been very busy with other codes when I closed it.

**Closed** 2019-12-26 00:04 UTC
Labels: bug
