### ISSUE TITLE
Don't pollute the org.lxde namespace

### ISSUE THREAD

**Issue by agaida** [lxqt/lximage-qt#125] opened 2018-03-26 21:47 UTC
```
src/CMakeLists.txt:    org.lxde.LxImage.Application.xml
src/application.cpp:static const char* serviceName = "org.lxde.LxImage";
src/application.cpp:static const char* ifaceName = "org.lxde.LxImage.Application";
src/org.lxde.LxImage.Application.xml:  <interface name="org.lxde.LxImage.Application">
```
Dunno if that is the best of all ideas

**Comment by stefonarch** [comment] 2022-01-07 16:33
Duplicate of https://github.com/lxqt/lximage-qt/issues/124

**Closed** 2022-01-07 16:34 UTC
